apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: auto-demo-container
        image: bonov/nginx-host:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
services:
  nginx-host:
    build: nginx/
    ports:
    - "80:80"
    
    
   
