apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-host
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: redis-host
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: redis-host
    spec:
      containers:
      - name: redis-host
        image: bonov/redis-host:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: redis-host
  labels:
    app: redis-host
spec:
  type: NodePort
  ports:
  - port: 9001
    nodePort: 30006
    protocol: TCP
  selector:
    app: redis-host
